### ISSUE TITLE
Install script needed

### ISSUE THREAD

**Issue by kewashi** [open-dash/HousePanel#1]
Need to provide an easy to use installation script in the style of Wordpress installation.

**Comment by smashim** [comment]
Ken,
I am curious if you have made anymore progress on your installation script?
In its current form for users like myself, the install is just too complicated and over my skills level.
Keep up the great work!

**Comment by kewashi** [comment]
I have not made any progress on this front. All efforts have been in updating the app itself. I will look into this soon though. The hardest part is setting up a rPI server so I think I can find an existing script for that. 
Ken
    	

    	________________________________Ken Washingtonken@kenw.com
    
  



On Fri, Dec 7, 2018 at 6:46 AM -0500, "smashim" <notifications@github.com> wrote:












Ken,

I am curious if you have made anymore progress on your installation script?

In its current form for users like myself, the install is just too complicated and over my skills level.

Keep up the great work!

**Comment by smashim** [comment]
Thanks for the update Ken....... really appreciate it and good work overall
!!!

pete

**Comment by kewashi** [comment]
The install script has been written. To use grab the file install.sh in the main repo and run in a standard rPi Linux bash window as

bash ./install.sh

**Comment by smashim** [comment]
Awesome! I will try to play with it this weekend.
Happy holidays

pete

**Comment by kewashi** [comment]
install.sh has been implemented.
