### ISSUE TITLE
Don't turn tile on/off when dragging stops

### ISSUE THREAD

**Issue by nitwitgit** [open-dash/HousePanel#19]
Need to capture the mouse up event when it is at the end of a drag. Otherwise it turns my lights on/off and drives my wife nuts.

If we implement the 'menu mode' while in panel view, this would go away (only drag tiles when the menu is open.)

**Comment by kewashi** [comment]
I fixed this in the sliderhue branch that isn't yet merged in, so I will move that part into the master thread.

**Comment by kewashi** [comment]
Okay - I checked and this fix is already in the master branch, but it only applies when dragging on the title bar. I will keep this issue open until I find a fix for the main tile too.

**Comment by kewashi** [comment]
Resolved with new option to set Operate or Drag or Reorder modes
