### ISSUE TITLE
Empty room bug

### ISSUE THREAD

**Issue by kewashi** [open-dash/HousePanel#22]
Rooms disappear when empty upon start and edit

**Comment by kewashi** [comment]
I could not replicate this bug

**Comment by nekkidtruth** [comment]
This bug still happens.

**Comment by blankman373** [comment]
Hi this is still happening. The room doesn't completely disappear. It still appears on the tab in the main view, and the name appears on the table in options view. HOWEVER, there is no checkbox column underneath it. For example, by default, HP creates Kitchen, Family, Living, Office, Bedrooms, Outside and Music. I moved all my devices into the Kitchen and saved. Going back into options, the checkboxes are only there for Kitchen, almost as if that cell has been "colspan=7". The only way to fix it is to manually edit the hmoptions.cfg and add the rooms back under the "things" heading with empty brackets. I'm attaching an image in hopes it helps explain it better than i can. 

<img width="1104" alt="screen shot 2018-03-11 at 10 15 23 pm" src="https://user-images.githubusercontent.com/6708764/37266765-baa91c60-2579-11e8-98b0-a52e312824a0.png">

**Comment by kewashi** [comment]
I think this has been fixed now. Please let me know.
