### ISSUE TITLE
After device(s) authorization, I get an error page

### ISSUE THREAD

**Issue by nawaidrana** [open-dash/HousePanel#27]
I am running on raspeberry pi, and after going to my local installation of housepanel, it takes me to oath smartthings auth page, and after I select all my devices, I get to a cannot load page error:

http://xxx.xx.x.x/housepanel.php?code=QoAMzw

This page isn’t working
192.168.86.57 is currently unable to handle this request.
HTTP ERROR 500

I even changed housepanel directory to 777 just in case if it was permission issue, but that didnt do anything either.

**Comment by kewashi** [comment]
Upgrade to latest version. Also confirm you have cURL installed and working. Should fix your issue.

**Comment by jimmyeao** [comment]
Just set this up from scratch, getting the same http 500 error - using a raspi

**Comment by jimmyeao** [comment]
Edit -php-curl wasnt installed although curl was, must have missed this step

**Comment by kewashi** [comment]
these issues have been resolved with latest version
