### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [open-dash/HousePanel#28]
Hi . I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard.
Mirza zulfan

**Comment by kewashi** [comment]
Sorry I didn’t see this. I welcome any help you offer. Just submit it here

**Comment by mirzazulfan** [comment]
Thanks for your response sir. I'll do my best. :)

**Comment by mirzazulfan** [comment]
Hi @kewashi .. I've designed a logo for you, what do you think? 
![house panel](https://user-images.githubusercontent.com/36124339/44132100-681ca3c6-a081-11e8-860f-a1ea56434bbf.png)
If you need to change, please let me know.

**Comment by Bluenoser** [comment]
Hi @kewashi,

  How about this logo?

![house_panel_icon_small](https://user-images.githubusercontent.com/1642241/45552681-1cf70500-b808-11e8-8d09-58c46923fd86.png)

**Comment by kewashi** [comment]
I like this one...  wonder if it could be slightly altered to include some sensor elements ... like a switch or bulb icon in the quadrants?

**Comment by Bluenoser** [comment]
As requested:

![house_panel_icon_small](https://user-images.githubusercontent.com/1642241/45827137-326aa400-bccc-11e8-878b-473b7a1fcfa8.png)
