### ISSUE TITLE
Unable to change Weather Location

### ISSUE THREAD

**Issue by jimmyeao** [open-dash/HousePanel#31]
Have tried editing the file forecast.html to have my location, but now I just get a small blank box with no weather details.
I changed your location to
https://forecast7.com/en/53d19n0d47/branston/?unit=uk
and tried
https://forecast7.com/en/53d19n0d47/branston/
with no joy.
I also changed the forecast_accu.html
to
https://www.accuweather.com/en/gb/branston/ln4-1/weather-forecast/716432 
but the changes arent reflected, it stays with the out the box configuration somehow

**Comment by kewashi** [comment]
Weather frames load either the forecast.html file or the Accuweather.html file. Edit both of these and you will get the behavior you want.
