### ISSUE TITLE
Switches not working

### ISSUE THREAD

**Issue by gwiddison** [open-dash/HousePanel#32]
Have just installed House Panel for the first time, Smartthings & rPi, all seems to authorise ok, icons all there and these reflect changes when I turn something on or off but I cannot turn things on or off from House panel itself, cursor changes to a finger when I hover over icon but nothing happens when I click, any ideas where I should be looking to fix this??

**Comment by gwiddison** [comment]
Slight update, the switches DO work but only by clicking on the very top of the tile between the light icon and the title bar, would like to be able to change to turn on and off by clicking anywhere on the icon ideally

**Comment by kewashi** [comment]
Please try the latest version. I have not been able to replicate your issue. Clicking anywhere on the icon should trigger the switch.
